# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish to github pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3.1.1
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: make pages-folder
      run: mkdir -p pages
    - name: Build with Gradle
      run: ./gradlew run
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
          branch: gh-pages
          folder: pages
